### ISSUE TITLE
Vue.use or Vue.component

### ISSUE THREAD

**Issue by Geminii** [stfalcon-studio/stf-vue-select#10]
Hi,
First, thanks a lot for your work. We really like your vue select component but we need to load it without `import` because our project import Vue with cdn.

Vue.use(StfVueSelect);
Vue.use(StfVueSelectOptions);

or :

Vue.component('stf-select', StfVueSelect);
Vue.component('stf-select-options', StfVueSelectOptions);

It's possible to include this way to load your library and minify it in dist file to load it ? :)
Thanks a lot.

**Comment by AndreySyagrovskiy** [comment]
@Geminii  Hello, You can use dist/lib/stf-vue-select.min.js and Vue.use(StfSelectPlugin)  now.
