### ISSUE TITLE
Select Options in Buefy Modal

### ISSUE THREAD

**Issue by pauloeduardorocha** [stfalcon-studio/stf-vue-select#12]
When showing the component in a Buefy modal, the select options are shown behind the modal.
It's not a style issue, the position is wrong in the dom.

**Comment by AndreySyagrovskiy** [comment]
@pauloeduardorocha  https://github.com/stfalcon-studio/stf-vue-select/issues/8 **please, read** . [There are solution for you.](https://github.com/stfalcon-studio/stf-vue-select/issues/8)
