### ISSUE TITLE
Dropdown shows under bootstrap 4 modal

### ISSUE THREAD

**Issue by kevingio** [stfalcon-studio/stf-vue-select#15]
It shows under the modal instead over the modal. I think this is just a css problem. I haven't found the solution, maybe anyone could help.

**Comment by AndreySyagrovskiy** [comment]
Hi @kevingio , Just read the last posts.  https://github.com/stfalcon-studio/stf-vue-select/issues/8
Kind regards Andrii

**Comment by kevingio** [comment]
It works, thanks @AndreySyagrovskiy
