### ISSUE TITLE
Be able to specify a container

### ISSUE THREAD

**Issue by Pixney-William** [stfalcon-studio/stf-vue-select#5]
I would like to be able to specify a container/wrapper element since it the positioning doesn't work right now if you for example use slidebars.js.

**Comment by AndreySyagrovskiy** [comment]
Thank you  @Pixney-William   for idea of improvement. Can you give me screen of bug or https://codepen.io/ example?

**Comment by AndreySyagrovskiy** [comment]
Calculation position was improved. Please check, @Pixney-William
