### ISSUE TITLE
Refresh position

### ISSUE THREAD

**Issue by trocho** [stfalcon-studio/stf-vue-select#6]
Is any way to refresh position of options? 
Sometime I have a problem like on the screenshot
![zaznaczenie_495](https://user-images.githubusercontent.com/9249585/30317748-52daecb4-97ab-11e7-82d3-7200d2d84cd0.png)

**Comment by AndreySyagrovskiy** [comment]
Calculation position was improved. Please check, @trocho !

**Comment by trocho** [comment]
Cool :) Thanks!

**Comment by AndreySyagrovskiy** [comment]
@trocho, you are welcome
