### ISSUE TITLE
Dropdown is not visible because attached behind all app elements

### ISSUE THREAD

**Issue by shershen08** [stfalcon-studio/stf-vue-select#8]
Due to this https://github.com/stfalcon-studio/stf-vue-select/blob/master/src/components/stf-select/StfSelect.vue#L89 the wrapper for the dropdown in attached to the DOM as the last element and may be not visible , for example when the some other popup is used.

![screenshot from 2017-12-19 18-04-30](https://user-images.githubusercontent.com/1363772/34169600-32fb9a9e-e4e8-11e7-8c95-ec06c7f0846e.png)

Maybe that could be better either to attach in front or have an option where to attach it (simmilar to #5 )

**Comment by shershen08** [comment]
Fix is
 - in CSS add to ```.stf-select__options.stf-select-options {z-index: 9999;}```
 - replace appending code with ```document.body.insertBefore(this.__selectOptionsWrapEl, document.body.childNodes[1])```

**Comment by AndreySyagrovskiy** [comment]
@shershen08  .stf-select__options.stf-select-options {z-index: 9999;} maybe it is enough? And you can add it as custom css of your site without changing the library, cause your solution is good but it is not all time suitable.

**Comment by shershen08** [comment]
CSS part of the solution - you are right one can add in the application styles. 
But the main problem is the position of the node in DOM, it's literally behind everything else. That's why adding it on top (or giving an option to do that may come handy).
I'll try to create a demo today and share with you

**Comment by AndreySyagrovskiy** [comment]
@shershen08 ok thank. I am looking forward your demo.

**Comment by shershen08** [comment]
here's a repo with a problem demo - https://github.com/shershen08/demo-stf-select-bug
in https://github.com/shershen08/demo-stf-select-bug/blob/master/src/App.vue I've added 2 variants of the select element , one in main part of the page, another in modal, that once can't be properly used

**Comment by AndreySyagrovskiy** [comment]
@shershen08  But z-index works in your case and document.body.insertBefore(this.__selectOptionsWrapEl, document.body.childNodes[1]) does not work. Maybe css is enough in your case.

**Comment by shershen08** [comment]
Hmm, strange, I'll check one again asap
Because in the real work app I had setup exactly as reproduced and z-index wasn't enough.

**Comment by AndreySyagrovskiy** [comment]
@shershen08  What is your browser? Is it all browsers or only one?
?

**Comment by shershen08** [comment]
it's about Chrome/FF

**Comment by AndreySyagrovskiy** [comment]
I add style and all worked to  https://github.com/shershen08/demo-stf-select-bug

.stf-select_opened .stf-select__options {
   z-index: 101;
}

**Comment by AndreySyagrovskiy** [comment]
@shershen08  check please

**Comment by shershen08** [comment]
Yes, it works. It's was my setup issue I guess.
